# Generated by Django 2.2.7 on 2020-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='malpractise',
            field=models.BooleanField(default=False),
        ),
    ]
