# Generated by Django 2.2.7 on 2020-08-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_profile_malpractise'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='add title', max_length=100),
            preserve_default=False,
        ),
    ]
